#include "ssm.h"
#include "unity.h"
#include "unity_fixture.h"
#include <stdio.h>

// #define MAX_NUM_MODULES 20
#define MAX_CELLS_PER_MODULE 12

// memory allocation for BMS_OUTPUT_T
bool balance_reqs[MAX_NUM_MODULES*MAX_CELLS_PER_MODULE];
BMS_CHARGE_REQ_T charge_req;
BMS_OUTPUT_T bms_output;

// memory allocation for BMS_INPUT_T
BMS_PACK_STATUS_T pack_status;
BMS_INPUT_T bms_input;

//memory allocation for BMS_STATE_T
BMS_CHARGER_STATUS_T charger_status;
uint32_t cell_voltages[MAX_NUM_MODULES*MAX_CELLS_PER_MODULE];
uint8_t module_cell_count[MAX_NUM_MODULES];
PACK_CONFIG_T pack_config;
BMS_STATE_T bms_state;

TEST_GROUP(SSM_Test);

TEST_SETUP(SSM_Test) {
    printf("\r(SSM/Init/Error)Setup...");
    
    bms_output.charge_req = &charge_req;
    bms_output.close_contactors = false;
    bms_output.balance_req = balance_reqs;
    bms_output.read_eeprom_packconfig = false;
    bms_output.check_packconfig_with_ltc = false;

    charge_req.charger_on = 0;
    charge_req.charge_current_mA = 0;
    charge_req.charge_voltage_mV = 0;

    bms_state.charger_status = &charger_status;
    bms_state.pack_config = &pack_config;
    bms_state.curr_mode = BMS_SSM_MODE_INIT;
    bms_state.init_state = BMS_INIT_OFF;
    bms_state.charge_state = BMS_CHARGE_OFF;
    bms_state.discharge_state = BMS_DISCHARGE_OFF;

    charger_status.connected = false;
    charger_status.error = false;

    pack_config.cell_min_mV = 2500;
    pack_config.cell_max_mV = 4200;
    pack_config.cell_capacity_cAh = 530;
    pack_config.num_modules = 1;
    pack_config.cell_charge_c_rating_cC = 70;
    pack_config.bal_on_thresh_mV = 4;
    pack_config.bal_off_thresh_mV = 1;
    pack_config.pack_cells_p = 6;
    pack_config.cv_min_current_mA = 50;
    pack_config.cv_min_current_ms = 60000;
    pack_config.cc_cell_voltage_mV = 4300;
    pack_config.cell_discharge_c_rating_cC = 200; // at 27 degrees C
    pack_config.max_cell_temp_dC = 50;
    pack_config.module_cell_count = module_cell_count;

    bms_input.hard_reset_line = false;
    bms_input.mode_request = BMS_SSM_MODE_STANDBY;
    bms_input.balance_mV = 0; // console request balance to mV
    bms_input.contactors_closed = false;
    bms_input.charger_on = false;
    bms_input.msTicks = 0;
    bms_input.pack_status = &pack_status;
    bms_input.eeprom_packconfig_read_done = false;
    bms_input.ltc_packconfig_check_done = false;
    bms_input.eeprom_read_error = false;

    memset(cell_voltages, 0, sizeof(cell_voltages));
    pack_status.cell_voltages_mV = cell_voltages;
    pack_status.pack_cell_max_mV = 0;
    pack_status.pack_cell_min_mV = 0xFFFFFFFF;
    pack_status.pack_current_mA = 0;
    pack_status.pack_voltage_mV = 0;
    pack_status.max_cell_temp_dC = 0;

    SSM_Init(&bms_input, &bms_state, &bms_output);   
}

TEST_TEAR_DOWN(SSM_Test) {
    printf("Teardown\r\n");
}

TEST(SSM_Test, ssm_init) {
    printf("ssm_init...");
    
    SSM_Init(&bms_input, &bms_state, &bms_output);
    TEST_ASSERT_EQUAL(bms_state.curr_mode, BMS_SSM_MODE_INIT);
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_OFF);

    TEST_ASSERT_FALSE(bms_output.read_eeprom_packconfig);
    TEST_ASSERT_FALSE(bms_output.check_packconfig_with_ltc);
    
}

TEST(SSM_Test, init_step_complete) {
    printf("init_step_complete...");

    
    Init_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT(bms_output.read_eeprom_packconfig);
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_READ_PACKCONFIG);

    bms_input.eeprom_packconfig_read_done = true;
    bms_input.ltc_packconfig_check_done = false;

    Init_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_CHECK_PACKCONFIG);
    TEST_ASSERT(bms_output.check_packconfig_with_ltc);
    
    bms_input.ltc_packconfig_check_done = true;

    Init_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_DONE);
    TEST_ASSERT_EQUAL(bms_state.curr_mode, BMS_SSM_MODE_STANDBY);
    TEST_ASSERT_FALSE(bms_output.check_packconfig_with_ltc);

    Init_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_DONE);
    TEST_ASSERT_EQUAL(bms_state.curr_mode, BMS_SSM_MODE_STANDBY);
    
}

TEST(SSM_Test, init_step_blocked) {
    printf("init_step_blocked...");
    Init_Step(&bms_input, &bms_state, &bms_output); 
    Init_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT(bms_output.read_eeprom_packconfig);
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_READ_PACKCONFIG);
}

TEST(SSM_Test, is_valid_jump) {
    // Autogenerated with appropriate modifications
    //
    // states = ["STANDBY", "INIT", "CHARGE", "BALANCE", "DISCHARGE","ERROR"]
    // for state1 in states:
    //      for state2 in states:
    //          print("TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_" + state1 + ", BMS_SSM_MODE_" + state2 + "));")
    
    printf("is_valid_jump...");
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_STANDBY, BMS_SSM_MODE_STANDBY));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_STANDBY, BMS_SSM_MODE_INIT));
    TEST_ASSERT(Is_Valid_Jump(BMS_SSM_MODE_STANDBY, BMS_SSM_MODE_CHARGE));
    TEST_ASSERT(Is_Valid_Jump(BMS_SSM_MODE_STANDBY, BMS_SSM_MODE_BALANCE));
    TEST_ASSERT(Is_Valid_Jump(BMS_SSM_MODE_STANDBY, BMS_SSM_MODE_DISCHARGE));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_INIT, BMS_SSM_MODE_STANDBY));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_INIT, BMS_SSM_MODE_INIT));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_INIT, BMS_SSM_MODE_CHARGE));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_INIT, BMS_SSM_MODE_BALANCE));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_INIT, BMS_SSM_MODE_DISCHARGE));
    TEST_ASSERT(Is_Valid_Jump(BMS_SSM_MODE_CHARGE, BMS_SSM_MODE_STANDBY));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_CHARGE, BMS_SSM_MODE_INIT));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_CHARGE, BMS_SSM_MODE_CHARGE));
    TEST_ASSERT(Is_Valid_Jump(BMS_SSM_MODE_CHARGE, BMS_SSM_MODE_BALANCE));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_CHARGE, BMS_SSM_MODE_DISCHARGE));
    TEST_ASSERT(Is_Valid_Jump(BMS_SSM_MODE_BALANCE, BMS_SSM_MODE_STANDBY));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_BALANCE, BMS_SSM_MODE_INIT));
    TEST_ASSERT(Is_Valid_Jump(BMS_SSM_MODE_BALANCE, BMS_SSM_MODE_CHARGE));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_BALANCE, BMS_SSM_MODE_BALANCE));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_BALANCE, BMS_SSM_MODE_DISCHARGE));
    TEST_ASSERT(Is_Valid_Jump(BMS_SSM_MODE_DISCHARGE, BMS_SSM_MODE_STANDBY));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_DISCHARGE, BMS_SSM_MODE_INIT));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_DISCHARGE, BMS_SSM_MODE_CHARGE));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_DISCHARGE, BMS_SSM_MODE_BALANCE));
    TEST_ASSERT_FALSE(Is_Valid_Jump(BMS_SSM_MODE_DISCHARGE, BMS_SSM_MODE_DISCHARGE));
}

TEST(SSM_Test, is_state_done) {
    printf("is_state_done...");
    
    // test init not done state
    TEST_ASSERT_FALSE(Is_State_Done(&bms_state));

    bms_state.curr_mode = BMS_SSM_MODE_CHARGE;
    bms_state.charge_state = BMS_CHARGE_OFF;
    TEST_ASSERT(Is_State_Done(&bms_state));
    
    bms_state.curr_mode = BMS_SSM_MODE_DISCHARGE;
    bms_state.discharge_state = BMS_DISCHARGE_OFF;
    TEST_ASSERT(Is_State_Done(&bms_state));

    bms_state.curr_mode = BMS_SSM_MODE_STANDBY;
    TEST_ASSERT(Is_State_Done(&bms_state));
    
}

TEST(SSM_Test, ssm_step_start) {
    printf("ssm_step_start...");

    bms_state.curr_mode = BMS_SSM_MODE_STANDBY;
    bms_state.charge_state = BMS_CHARGE_OFF;
    bms_input.mode_request = BMS_SSM_MODE_DISCHARGE;
    SSM_Step(&bms_input, &bms_state, &bms_output);
    TEST_ASSERT_EQUAL(BMS_SSM_MODE_DISCHARGE, bms_state.curr_mode);

    bms_state.curr_mode = BMS_SSM_MODE_BALANCE;
    bms_state.charge_state = BMS_CHARGE_BAL;
    bms_input.mode_request = BMS_SSM_MODE_CHARGE;
    SSM_Step(&bms_input, &bms_state, &bms_output);
    TEST_ASSERT_EQUAL(BMS_SSM_MODE_CHARGE, bms_state.curr_mode);

    bms_state.curr_mode = BMS_SSM_MODE_CHARGE;
    bms_state.charge_state = BMS_CHARGE_CC;
    bms_input.mode_request = BMS_SSM_MODE_BALANCE;
    SSM_Step(&bms_input, &bms_state, &bms_output);
    TEST_ASSERT_EQUAL(BMS_SSM_MODE_BALANCE, bms_state.curr_mode);
}

TEST(SSM_Test, ssm_step) {
    printf("ssm_step...");

    bms_input.mode_request = BMS_SSM_MODE_DISCHARGE;
    SSM_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT(bms_output.read_eeprom_packconfig);
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_READ_PACKCONFIG);

    bms_input.eeprom_packconfig_read_done = true;
    
    SSM_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_CHECK_PACKCONFIG);
    TEST_ASSERT(bms_output.check_packconfig_with_ltc);
    
    bms_input.ltc_packconfig_check_done = true;

    SSM_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_DONE);
    TEST_ASSERT_EQUAL(bms_state.curr_mode, BMS_SSM_MODE_STANDBY);
    TEST_ASSERT_FALSE(bms_output.check_packconfig_with_ltc);

    SSM_Step(&bms_input, &bms_state, &bms_output); 
    TEST_ASSERT_EQUAL(bms_state.init_state, BMS_INIT_DONE);
    TEST_ASSERT_EQUAL(bms_state.curr_mode, BMS_SSM_MODE_DISCHARGE);
}


TEST_GROUP_RUNNER(SSM_Test) {
    RUN_TEST_CASE(SSM_Test, ssm_init);
    RUN_TEST_CASE(SSM_Test, init_step_complete);
    RUN_TEST_CASE(SSM_Test, init_step_blocked);
    RUN_TEST_CASE(SSM_Test, is_valid_jump);
    RUN_TEST_CASE(SSM_Test, is_state_done);
    RUN_TEST_CASE(SSM_Test, ssm_step_start);
    RUN_TEST_CASE(SSM_Test, ssm_step);
}

